Update Nextcloud

diff --git a/nextcloud/preHooks.yaml b/nextcloud/preHooks.yaml
--- a/nextcloud/preHooks.yaml
+++ b/nextcloud/preHooks.yaml
@@ -99,32 +99,39 @@ data:
     run_path() {
         local hook_folder_path="/docker-entrypoint-hooks.d/$1"
         local return_code=0
+        local found=0
 
-        if ! [ -d "${hook_folder_path}" ]; then
-            echo "=> Skipping the folder \"${hook_folder_path}\", because it doesn't exist"
+        echo "=> Searching for hook scripts (*.sh) to run, located in the folder \"${hook_folder_path}\""
+
+        if ! [ -d "${hook_folder_path}" ] || directory_empty "${hook_folder_path}"; then
+            echo "==> Skipped: the \"$1\" folder is empty (or does not exist)"
             return 0
         fi
 
-        echo "=> Searching for scripts (*.sh) to run, located in the folder: ${hook_folder_path}"
-
-        (
-            find "${hook_folder_path}" -maxdepth 1 -iname '*.sh' '(' -type f -o -type l ')' -print | sort | while read -r script_file_path; do
+        find "${hook_folder_path}" -maxdepth 1 -iname '*.sh' '(' -type f -o -type l ')' -print | sort | (
+            while read -r script_file_path; do
                 if ! [ -x "${script_file_path}" ]; then
-                    echo "==> The script \"${script_file_path}\" was skipped, because it didn't have the executable flag"
+                    echo "==> The script \"${script_file_path}\" was skipped, because it lacks the executable flag"
+                    found=$((found-1))
                     continue
                 fi
 
                 echo "==> Running the script (cwd: $(pwd)): \"${script_file_path}\""
-
+                found=$((found+1))
                 run_as "${script_file_path}" || return_code="$?"
 
                 if [ "${return_code}" -ne "0" ]; then
-                    echo "==> Failed at executing \"${script_file_path}\". Exit code: ${return_code}"
+                    echo "==> Failed at executing script \"${script_file_path}\". Exit code: ${return_code}"
                     exit 1
                 fi
 
-                echo "==> Finished the script: \"${script_file_path}\""
+                echo "==> Finished executing the script: \"${script_file_path}\""
             done
+            if [ "$found" -lt "1" ]; then
+                echo "==> Skipped: the \"$1\" folder does not contain any valid scripts"
+            else
+                echo "=> Completed executing scripts in the \"$1\" folder"
+            fi
         )
     }
 
@@ -158,9 +165,6 @@ data:
 
     # Dennis: Install depedencies for previews
     apt-get update && apt-get install -y ffmpeg imagemagick ghostscript
-
-    # Dennis: update rights for ImageMagick
-    sed -i 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/g' /etc/ImageMagick-6/policy.xml
 
     if expr "$1" : "apache" 1>/dev/null; then
         if [ -n "${APACHE_DISABLE_REWRITE_IP+x}" ]; then
@@ -200,14 +204,22 @@ data:
                 echo 'session.save_handler = redis'
                 # check if redis host is an unix socket path
                 if [ "$(echo "$REDIS_HOST" | cut -c1-1)" = "/" ]; then
-                  if [ -n "${REDIS_HOST_PASSWORD+x}" ]; then
+                if [ -n "${REDIS_HOST_PASSWORD+x}" ]; then
+                    if [ -n "${REDIS_HOST_USER+x}" ]; then
+                    echo "session.save_path = \"unix://${REDIS_HOST}?auth[]=${REDIS_HOST_USER}&auth[]=${REDIS_HOST_PASSWORD}\""
+                    else
                     echo "session.save_path = \"unix://${REDIS_HOST}?auth=${REDIS_HOST_PASSWORD}\""
-                  else
+                    fi
+                else
                     echo "session.save_path = \"unix://${REDIS_HOST}\""
-                  fi
+                fi
                 # check if redis password has been set
                 elif [ -n "${REDIS_HOST_PASSWORD+x}" ]; then
-                    echo "session.save_path = \"tcp://${REDIS_HOST}:${REDIS_HOST_PORT:=6379}?auth=${REDIS_HOST_PASSWORD}\""
+                    if [ -n "${REDIS_HOST_USER+x}" ]; then
+                        echo "session.save_path = \"tcp://${REDIS_HOST}:${REDIS_HOST_PORT:=6379}?auth[]=${REDIS_HOST_USER}&auth[]=${REDIS_HOST_PASSWORD}\""
+                    else
+                        echo "session.save_path = \"tcp://${REDIS_HOST}:${REDIS_HOST_PORT:=6379}?auth=${REDIS_HOST_PASSWORD}\""
+                    fi
                 else
                     echo "session.save_path = \"tcp://${REDIS_HOST}:${REDIS_HOST_PORT:=6379}\""
                 fi
@@ -253,7 +265,6 @@ data:
                     run_as 'php /var/www/html/occ app:list' | sed -n "/Enabled:/,/Disabled:/p" > /tmp/list_before
                 fi
                 if [ "$(id -u)" = 0 ]; then
-                    # Dennis: owned by my user
                     rsync_options="-rlDog --chown dennis:dennis"
                 else
                     rsync_options="-rlD"
@@ -274,6 +285,7 @@ data:
                     file_env NEXTCLOUD_ADMIN_PASSWORD
                     file_env NEXTCLOUD_ADMIN_USER
 
+                    install=false
                     if [ -n "${NEXTCLOUD_ADMIN_USER+x}" ] && [ -n "${NEXTCLOUD_ADMIN_PASSWORD+x}" ]; then
                         # shellcheck disable=SC2016
                         install_options='-n --admin-user "$NEXTCLOUD_ADMIN_USER" --admin-pass "$NEXTCLOUD_ADMIN_PASSWORD"'
@@ -289,7 +301,6 @@ data:
                         file_env POSTGRES_PASSWORD
                         file_env POSTGRES_USER
 
-                        install=false
                         if [ -n "${SQLITE_DATABASE+x}" ]; then
                             echo "Installing with SQLite database"
                             # shellcheck disable=SC2016
@@ -313,7 +324,7 @@ data:
                             echo "Starting nextcloud installation"
                             max_retries=10
                             try=0
-                            until run_as "php /var/www/html/occ maintenance:install $install_options" || [ "$try" -gt "$max_retries" ]
+                            until  [ "$try" -gt "$max_retries" ] || run_as "php /var/www/html/occ maintenance:install $install_options"
                             do
                                 echo "Retrying install..."
                                 try=$((try+1))
@@ -325,18 +336,23 @@ data:
                             fi
                             if [ -n "${NEXTCLOUD_TRUSTED_DOMAINS+x}" ]; then
                                 echo "Setting trusted domains…"
+                    set -f # turn off glob
                                 NC_TRUSTED_DOMAIN_IDX=1
-                                for DOMAIN in $NEXTCLOUD_TRUSTED_DOMAINS ; do
-                                    DOMAIN=$(echo "$DOMAIN" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
-                                    run_as "php /var/www/html/occ config:system:set trusted_domains $NC_TRUSTED_DOMAIN_IDX --value=$DOMAIN"
+                                for DOMAIN in ${NEXTCLOUD_TRUSTED_DOMAINS}; do
+                                    DOMAIN=$(echo "${DOMAIN}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
+                                    run_as "php /var/www/html/occ config:system:set trusted_domains $NC_TRUSTED_DOMAIN_IDX --value=\"${DOMAIN}\""
                                     NC_TRUSTED_DOMAIN_IDX=$((NC_TRUSTED_DOMAIN_IDX+1))
                                 done
+                    set +f # turn glob back on
                             fi
 
                             run_path post-installation
-                        else
-                            echo "Please run the web-based installer on first connect!"
-                        fi
+                fi
+                    fi
+            # not enough specified to do a fully automated installation
+                    if [ "$install" = false ]; then
+                        echo "Next step: Access your instance to finish the web-based installation!"
+                        echo "Hint: You can specify NEXTCLOUD_ADMIN_USER and NEXTCLOUD_ADMIN_PASSWORD and the database variables _prior to first launch_ to fully automate initial installation."
                     fi
                 # Upgrade
                 else
@@ -361,13 +377,18 @@ data:
             fi
         ) 9> /var/www/html/nextcloud-init-sync.lock
 
+        # warn if config files on persistent storage differ from the latest version of this image
+        for cfgPath in /usr/src/nextcloud/config/*.php; do
+            cfgFile=$(basename "$cfgPath")
+
+            if [ "$cfgFile" != "config.sample.php" ] && [ "$cfgFile" != "autoconfig.php" ]; then
+                if ! cmp -s "/usr/src/nextcloud/config/$cfgFile" "/var/www/html/config/$cfgFile"; then
+                    echo "Warning: /var/www/html/config/$cfgFile differs from the latest version of this image at /usr/src/nextcloud/config/$cfgFile"
+                fi
+            fi
+        done
+
         run_path before-starting
     fi
-
-    echo "⚠️⚠️⚠️"
-    echo "This image is maintained by community volunteers and designed for expert use."
-    echo "For quick and easy deployment that supports the full set of Nextcloud Hub features, use the Nextcloud All-in-One docker container maintained by Nextcloud GmbH."
-    echo "See https://github.com/nextcloud/all-in-one#nextcloud-all-in-one"
-    echo "⚠️⚠️⚠️ "
 
     exec "$@"
